### ISSUE TITLE
Pairing Problem

### ISSUE THREAD

**Issue by TetrixGauss** [BharathVishal/Message-communication-using-Wearable-Data-Layer-Android-Wear-OS#3] opened 2023-02-01 11:05 UTC
Hello! First of all let me thank you for your repository! It's amazing. 

I am trying your code and i have paired the two devices (mobile and wearable) via bluetooth but when the mobile search the wearable I get the message 
`A wearable device is paired but the wearable app on your watch isn't open. Launch the wearable app and try again.`

I have tried to reopen the wearable application but nothing. 

Any suggestions?

**Comment by BharathVishal** [comment] 2023-02-01 11:12
Hi,
Once you have paired the wearable device through "Wear OS by Google Smartwatch" app, you need to make sure that this app is open on both the wearable and mobile device. 

When this app is launched and kept open on both the mobile and wearable device, you can transfer or receive messages and the message you mentioned won't be displayed. This was the intended functionality as the wearable data-layer listener is tied to the activity lifecycle. 

Hope this helps.

**Comment by TetrixGauss** [comment] 2023-02-01 11:37
The wearable is Samsung Watch 4 and as i read the wear os by google doesnt work. Any suggestions?

**Comment by BharathVishal** [comment] 2023-02-01 11:45
Hi,
Could you try pairing your Samsung Watch 4 using the "Galaxy Wearable (Samsung Gear)" app and then install this app on your wearable and your mobile device. Make sure bluetooth is switched on and keep the activity of this app open on both the devices. This should fix probably the connectivity issue and then you can transfer messages between the devices. Hope this helps.

**Comment by TetrixGauss** [comment] 2023-02-01 11:47
It is actually paired with the Galaxy Wearable app

**Comment by TetrixGauss** [comment] 2023-02-01 12:37
@BharathVishal Any other suggestions ?

**Comment by BharathVishal** [comment] 2023-02-01 13:07
Hi,
I couldn't think of any other suggestions for this issue at the moment. Based on the message flow it means that the wearable device is actually returned by the wearable data layer's getNodes method, but the message isn't receiving due to the wearable app not being in foreground. 

Could you keep this app's activity open on your wearable device without any sleep enabled like shown in this [screenshot](https://raw.githubusercontent.com/BharathVishal/Message-communication-using-Wearable-Data-Layer-Android-Wear-OS/master/Screenshots/1.png) and your mobile version open as shown in this [screenshot](https://github.com/BharathVishal/Message-communication-using-Wearable-Data-Layer-Android-Wear-OS/blob/master/Screenshots/2.png?s=10). 

Also, please check if both the devices have Google Play services installed.

**Comment by TetrixGauss** [comment] 2023-02-01 13:13
Actually after a while the wearable part maybe is going to sleep..Am i doing something wrong?

**Comment by BharathVishal** [comment] 2023-02-01 13:18
Hi,
The issue seems to be due to the watch going into sleep mode which is triggering the Activity's onPause() method that removes the wearable data-layer listener. Increase the screen timeout of your wearable device to fix this issue. 

Goto _Settings_ -> _Display_ -> _Screen Timeout_-> Set it to _One minute_. 

Please check if this fixes the issue. You need to make sure that the app on the wearable device doesn't goto background or enter into ambient mode. This should possibly fix the issue.  

An alternative way to fix to the issue is by moving the _removelistener_ methods to onStop of the MainActivity's class.

**Comment by BharathVishal** [comment] 2023-02-01 13:31
Hi,
Could you check the suggestions in the previous message, so I can close this issue?

**Comment by TetrixGauss** [comment] 2023-02-01 13:37
I did all the above but still the onMessageReceived is never called

**Comment by TetrixGauss** [comment] 2023-02-01 13:38
All i want is to send from wearable to mobile. Is there any other way to do it?

**Comment by BharathVishal** [comment] 2023-02-01 13:46
Hi,
The only way i can check the reason for this issue is by debugging with a Galaxy Watch 4 or a Samsung wearable device. Since, the app works as intended on my Fossil Gen 4 device, paired through Wear OS app and in Android Studio Wear OS emulators, I'm unable to find out the exact reason as to why this is happening only on Galaxy watch devices.

**Closed as completed** 2023-02-01 13:52 UTC
